CREATE VIEW [dbo].[ADMIN_COMPANYEMAIL_REMINDER_TABLE]
AS
SELECT        dbo.ADMIN_COMPANY_INFORMATION.Id, dbo.ADMIN_COMPANY_INFORMATION.COMPANY_NAME, dbo.ADMIN_COMPANY_INFORMATION.EMAIL, dbo.ADMIN_COMPANY_INFORMATION.COMPANY_ID, 
                         dbo.ADMIN_CONCESSIONS_INFORMATION.OPEN_DATE, dbo.ADMIN_CONCESSIONS_INFORMATION.CLOSE_DATE, dbo.ADMIN_CONCESSIONS_INFORMATION.EMAIL_REMARK, 
                         dbo.ADMIN_CONCESSIONS_INFORMATION.Company_ID AS Expr1
FROM            dbo.ADMIN_COMPANY_INFORMATION INNER JOIN
                         dbo.ADMIN_CONCESSIONS_INFORMATION ON dbo.ADMIN_COMPANY_INFORMATION.COMPANY_ID = dbo.ADMIN_CONCESSIONS_INFORMATION.Company_ID