CREATE VIEW [dbo].[VW_GEOPHYSICAL_ACTIVITIES_PROCESSING_SUM_BY_YEAR]
AS
SELECT     Year, SUM(CAST(Geo_Quantum_of_Data AS int)) AS Geo_Quantum_of_Data
FROM         dbo.VW_GEOPHYSICAL_ACTIVITIES_PROCESSING
GROUP BY Year