CREATE VIEW [dbo].[WP_COUNT_PRESENTATION_CATERGORY_BY_YEAR_STATUS_COMPANYNAME]
AS
SELECT     TOP (100) PERCENT COUNT(Status_) AS count, Year, Status_, CompanyName
FROM         dbo.ADMIN_CONCESSIONS_INFORMATION
GROUP BY Year, Status_, CompanyName
ORDER BY Year