CREATE VIEW [dbo].[WP_HSE_ACCIDENT_INCIDENCE_REPORTING_TYPE_OF_ACCIDENT_NEW_by_consequences]
AS
SELECT     TOP (100) PERCENT SUM(CAST(Frequency AS int)) AS sum_accident, Year_of_WP, Consequence
FROM         dbo.HSE_ACCIDENT_INCIDENCE_REPORTING_TYPE_OF_ACCIDENT_NEW
WHERE     (Cause IN ('EQUIPMENT FAILURE', 'HUMAN ERROR', 'MYSTERY SPILLS', 'SABOTAGE'))
GROUP BY Year_of_WP, Consequence
ORDER BY Year_of_WP