CREATE VIEW [dbo].[WP_RESERVES_REPLACEMENT_RATIO_VALUE_TO_BE_PIVOTTED]
AS


SELECT     CompanyName, SUM(CAST(RESERVES_REPLACEMENT_RATIO_VALUE AS int)) AS RESERVES_REPLACEMENT_RATIO_VALUE, Year_of_WP
FROM         dbo.RESERVES_REPLACEMENT_RATIO
GROUP BY CompanyName, Year_of_WP
