CREATE TABLE [dbo].[BUDGET_CAPEX_OPEX] (
    [Id]                INT           IDENTITY (1, 1) NOT NULL,
    [OML_ID]            VARCHAR (200) NULL,
    [OML_Name]          VARCHAR (200) NULL,
    [CompanyName]       VARCHAR (500) NULL,
    [Companyemail]      VARCHAR (500) NULL,
    [Year_of_WP]        VARCHAR (100) NULL,
    [Item_Type]         VARCHAR (500) NULL,
    [Item_Description]  VARCHAR (500) NULL,
    [naira]             VARCHAR (500) NULL,
    [dollar]            VARCHAR (500) NULL,
    [Dollar_equivalent] VARCHAR (500) NULL,
    [remarks]           VARCHAR (500) NULL,
    [Created_by]        VARCHAR (100) NULL,
    [Updated_by]        VARCHAR (100) NULL,
    [Date_Created]      DATETIME      NULL,
    [Date_Updated]      DATETIME      NULL,
    [Contract_Type]     VARCHAR (50)  NULL,
    [Terrain]           VARCHAR (50)  NULL,
    [Consession_Type]   VARCHAR (50)  NULL,
    [COMPANY_ID]        VARCHAR (100) NULL,
    [CompanyNumber]     INT           NULL,
    [Field_ID]          INT           NULL,
    CONSTRAINT [PK_BUDGET_CAPEX_OPEX] PRIMARY KEY CLUSTERED ([Id] ASC)
);

