CREATE TABLE [dbo].[BUDGET_CAPEXs] (
    [ID]                        INT            IDENTITY (1, 1) NOT NULL,
    [OmL_Name]                  NVARCHAR (MAX) NULL,
    [OmL_ID]                    NVARCHAR (MAX) NULL,
    [CompanyName]               NVARCHAR (MAX) NULL,
    [Companyemail]              NVARCHAR (MAX) NULL,
    [Year_of_WP]                NVARCHAR (MAX) NULL,
    [Company_ID]                NVARCHAR (MAX) NULL,
    [CompanyNumber]             INT            NULL,
    [Acquisition]               NVARCHAR (MAX) NULL,
    [Processing]                NVARCHAR (MAX) NULL,
    [Reprocessing]              NVARCHAR (MAX) NULL,
    [Exploratory_Well_Drilling] NVARCHAR (MAX) NULL,
    [Appraisal_Well_Drilling]   NVARCHAR (MAX) NULL,
    [Development_Well_Drilling] NVARCHAR (MAX) NULL,
    [Workover_Operations]       NVARCHAR (MAX) NULL,
    [Completions]               NVARCHAR (MAX) NULL,
    [Flowlines]                 NVARCHAR (MAX) NULL,
    [Pipelines]                 NVARCHAR (MAX) NULL,
    [Generators]                NVARCHAR (MAX) NULL,
    [Turbines_Compressors]      NVARCHAR (MAX) NULL,
    [Buildings]                 NVARCHAR (MAX) NULL,
    [Other_Equipment]           NVARCHAR (MAX) NULL,
    [Civil_Works]               NVARCHAR (MAX) NULL,
    [Other_Costs]               NVARCHAR (MAX) NULL,
    [Created_by]                NVARCHAR (MAX) NULL,
    [Updated_by]                NVARCHAR (MAX) NULL,
    [Date_Created]              DATETIME2 (7)  NULL,
    [Date_Updated]              DATETIME2 (7)  NULL,
    CONSTRAINT [PK_BUDGET_CAPEXs] PRIMARY KEY CLUSTERED ([ID] ASC)
);

