CREATE TABLE [dbo].[DRILLING_OPERATIONS_CATEGORIES_OF_WELLS] (
    [Id]                                          INT            IDENTITY (1, 1) NOT NULL,
    [OML_ID]                                      VARCHAR (200)  NULL,
    [OML_Name]                                    VARCHAR (200)  NULL,
    [CompanyName]                                 VARCHAR (500)  NULL,
    [Companyemail]                                VARCHAR (500)  NULL,
    [Year_of_WP]                                  VARCHAR (100)  NULL,
    [Category]                                    VARCHAR (200)  NULL,
    [Actual_No_Drilled_in_Current_Year]           VARCHAR (100)  NULL,
    [Proposed_No_Drilled]                         VARCHAR (500)  NULL,
    [Processing_Fees_Paid]                        VARCHAR (500)  NULL,
    [Comments]                                    VARCHAR (MAX)  NULL,
    [No_of_wells_cored]                           VARCHAR (500)  NULL,
    [Actual_year]                                 VARCHAR (300)  NULL,
    [proposed_year]                               VARCHAR (300)  NULL,
    [Created_by]                                  VARCHAR (100)  NULL,
    [Updated_by]                                  VARCHAR (100)  NULL,
    [Date_Created]                                DATETIME       NULL,
    [Date_Updated]                                DATETIME       NULL,
    [well_type]                                   VARCHAR (50)   NULL,
    [well_trajectory]                             VARCHAR (50)   NULL,
    [spud_date]                                   DATE           NULL,
    [well_cost]                                   VARCHAR (50)   NULL,
    [Number_of_Days_to_Total_Depth]               VARCHAR (50)   NULL,
    [Well_Status_and_Depth]                       VARCHAR (100)  NULL,
    [Contract_Type]                               VARCHAR (50)   NULL,
    [Terrain]                                     VARCHAR (50)   NULL,
    [well_name]                                   VARCHAR (500)  NULL,
    [Consession_Type]                             VARCHAR (50)   NULL,
    [QUATER]                                      VARCHAR (50)   NULL,
    [Any_New_Discoveries]                         VARCHAR (50)   NULL,
    [Hydrocarbon_Counts]                          VARCHAR (50)   NULL,
    [State_the_field_where_Discovery_was_made]    VARCHAR (4999) NULL,
    [Core_Cost_USD]                               VARCHAR (20)   NULL,
    [Core_Depth_Interval]                         VARCHAR (20)   NULL,
    [Propose_well_names]                          VARCHAR (3000) NULL,
    [Actual_wells_name]                           VARCHAR (3000) NULL,
    [Terrain_Drill]                               VARCHAR (500)  NULL,
    [Water_depth]                                 VARCHAR (500)  NULL,
    [True_vertical_depth]                         VARCHAR (500)  NULL,
    [Depth_refrence]                              VARCHAR (500)  NULL,
    [Rig_type]                                    VARCHAR (500)  NULL,
    [Rig_Name]                                    VARCHAR (500)  NULL,
    [Target_reservoir]                            VARCHAR (500)  NULL,
    [Surface_cordinates_for_each_well_in_degrees] VARCHAR (500)  NULL,
    [Location_name]                               VARCHAR (3000) NULL,
    [Proposed_cost_per_well]                      VARCHAR (500)  NULL,
    [Basin]                                       VARCHAR (500)  NULL,
    [Measured_depth]                              VARCHAR (500)  NULL,
    [FieldDiscoveryUploadFilePath]                VARCHAR (500)  NULL,
    [HydrocarbonCountUploadFilePath]              VARCHAR (500)  NULL,
    [COMPANY_ID]                                  VARCHAR (100)  NULL,
    [Cored]                                       VARCHAR (100)  NULL,
    [Actual_Proposed]                             VARCHAR (100)  NULL,
    [WellName]                                    VARCHAR (2000) NULL,
    [CompanyNumber]                               INT            NULL,
<<<<<<< HEAD
    CONSTRAINT [PK_DRILLING_OPERATIONS_CATEGORIES_OF_WELLS] PRIMARY KEY CLUSTERED ([Id] ASC)
);

=======
    [Field_ID]                                    INT            NULL,
    CONSTRAINT [PK_DRILLING_OPERATIONS_CATEGORIES_OF_WELLS] PRIMARY KEY CLUSTERED ([Id] ASC)
);



>>>>>>> origin/main
