CREATE TABLE [dbo].[HSE_TECHNICAL_SAFETY_CONTROL_STUDIES_NEW] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [OML_ID]               VARCHAR (200)  NULL,
    [OML_Name]             VARCHAR (200)  NULL,
    [CompanyName]          VARCHAR (500)  NULL,
    [Companyemail]         VARCHAR (500)  NULL,
    [Year_of_WP]           VARCHAR (100)  NULL,
    [facility]             VARCHAR (500)  NULL,
    [study_type]           VARCHAR (500)  NULL,
    [facility_location]    VARCHAR (3999) NULL,
    [approval_status]      VARCHAR (3900) NULL,
    [remarks]              VARCHAR (3999) NULL,
    [Created_by]           VARCHAR (100)  NULL,
    [Updated_by]           VARCHAR (100)  NULL,
    [Date_Created]         DATETIME       NULL,
    [Date_Updated]         DATETIME       NULL,
    [Contract_Type]        VARCHAR (50)   NULL,
    [Terrain]              VARCHAR (50)   NULL,
    [Consession_Type]      VARCHAR (50)   NULL,
    [COMPANY_ID]           VARCHAR (100)  NULL,
    [CompanyNumber]        INT            NULL,
    [Field_ID]             INT            NULL,
    [type_of_facility]     VARCHAR (MAX)  NULL,
    [number_of_facilities] VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_HSE_TECHNICAL_SAFETY_CONTROL_STUDIES_NEW] PRIMARY KEY CLUSTERED ([Id] ASC)
);

