CREATE TABLE [dbo].[HSE_SAFETY_CULTURE_TRAINING] (
    [Id]                             INT            IDENTITY (1, 1) NOT NULL,
    [OML_ID]                         VARCHAR (200)  NULL,
    [OML_Name]                       VARCHAR (200)  NULL,
    [CompanyName]                    VARCHAR (500)  NULL,
    [Companyemail]                   VARCHAR (500)  NULL,
    [Year_of_WP]                     VARCHAR (100)  NULL,
    [SafetyCurrentYearFilePath]      VARCHAR (3000) NULL,
    [SafetyLast2YearsFilePath]       VARCHAR (500)  NULL,
    [Created_by]                     VARCHAR (100)  NULL,
    [Updated_by]                     VARCHAR (100)  NULL,
    [Date_Created]                   DATETIME       NULL,
    [Date_Updated]                   DATETIME       NULL,
    [Consession_Type]                VARCHAR (50)   NULL,
    [Terrain]                        VARCHAR (50)   NULL,
    [Contract_Type]                  VARCHAR (50)   NULL,
    [SafetyCurrentYearFilename]      VARCHAR (100)  NULL,
    [SafetyLast2YearsFilename]       VARCHAR (100)  NULL,
    [COMPANY_ID]                     VARCHAR (100)  NULL,
    [CompanyNumber]                  INT            NULL,
    [Field_ID]                       INT            NULL,
    [AreThereTrainingPlansForHSE]    VARCHAR (MAX)  NULL,
    [EvidenceOfTrainingPlanFilename] VARCHAR (MAX)  NULL,
    [EvidenceOfTrainingPlanPath]     VARCHAR (MAX)  NULL,
    [Remark]                         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_HSE_SAFETY_CULTURE_TRAINING] PRIMARY KEY CLUSTERED ([Id] ASC)
);

