CREATE TABLE [dbo].[RESERVES_UPDATES_OIL_CONDENSATE] (
    [Id]                                               INT           IDENTITY (1, 1) NOT NULL,
    [OML_ID]                                           VARCHAR (200) NULL,
    [OML_Name]                                         VARCHAR (200) NULL,
    [CompanyName]                                      VARCHAR (500) NULL,
    [Companyemail]                                     VARCHAR (500) NULL,
    [Year_of_WP]                                       VARCHAR (100) NULL,
    [Reserves_as_at_MMbbl_P1]                          VARCHAR (500) NULL,
    [Additional_Reserves_as_at_]                       VARCHAR (500) NULL,
    [Total_Production_]                                VARCHAR (500) NULL,
    [Reserves_as_at_MMbbl]                             VARCHAR (MAX) NULL,
    [Company_Reserves_Year]                            VARCHAR (500) NULL,
    [Company_Reserves_Oil]                             VARCHAR (500) NULL,
    [Company_Reserves_Condensate]                      VARCHAR (500) NULL,
    [Company_Reserves_AG]                              VARCHAR (100) NULL,
    [Company_Reserves_NAG]                             VARCHAR (500) NULL,
    [Company_Reserves_AnnualOilProduction]             VARCHAR (500) NULL,
    [Company_Current_Year]                             VARCHAR (500) NULL,
    [Company_Current_Oil]                              VARCHAR (500) NULL,
    [Company_Current_Condensate]                       VARCHAR (500) NULL,
    [Company_Current_AG]                               VARCHAR (100) NULL,
    [Company_Current_NAG]                              VARCHAR (500) NULL,
    [Company_Current_AnnualOilProduction]              VARCHAR (500) NULL,
    [Fiveyear_Projection_Year]                         VARCHAR (500) NULL,
    [Fiveyear_Projection_Oil]                          VARCHAR (500) NULL,
    [Fiveyear_Projection_Condensate]                   VARCHAR (500) NULL,
    [Fiveyear_Projection_AG]                           VARCHAR (100) NULL,
    [Fiveyear_Projection_NAG]                          VARCHAR (500) NULL,
    [Fiveyear_Projection_AnnualOilProduction]          VARCHAR (500) NULL,
    [Company_Annual_Year]                              VARCHAR (500) NULL,
    [Company_Annual_Oil]                               VARCHAR (500) NULL,
    [Company_Annual_Condensate]                        VARCHAR (500) NULL,
    [Company_Annual_AG]                                VARCHAR (100) NULL,
    [Company_Annual_NAG]                               VARCHAR (500) NULL,
    [Company_Annual_AnnualOilProduction]               VARCHAR (500) NULL,
    [Reserves_Addition_Was_there_any_Reserve_Addition] VARCHAR (500) NULL,
    [Reserves_Addition_Reason_for_Addition]            VARCHAR (500) NULL,
    [Reserves_Addition_Condensate]                     VARCHAR (500) NULL,
    [Reserves_Addition_AG]                             VARCHAR (100) NULL,
    [Reserves_Addition_NAG]                            VARCHAR (500) NULL,
    [Reserves_Addition_Oil]                            VARCHAR (500) NULL,
    [Reserves_Decline_Was_there_a_decline_in_reserve]  VARCHAR (500) NULL,
    [Reserves_Decline_Reason_for_Decline]              VARCHAR (500) NULL,
    [Reserves_Decline_Condensate]                      VARCHAR (500) NULL,
    [Reserves_Decline_AG]                              VARCHAR (100) NULL,
    [Reserves_Decline_NAG]                             VARCHAR (500) NULL,
    [Reserves_Decline_Oil]                             VARCHAR (500) NULL,
    [Reservoir_Performance_Timeline]                   VARCHAR (500) NULL,
    [Reservoir_Performance_Reservoir]                  VARCHAR (500) NULL,
    [Reservoir_Performance_Reservoir Pressure]         VARCHAR (500) NULL,
    [Reservoir_Performance_WCT]                        VARCHAR (100) NULL,
    [Reservoir_Performance_GOR]                        VARCHAR (500) NULL,
    [Reservoir_Performance_Sand_Cut]                   VARCHAR (500) NULL,
    [Consession_Type]                                  VARCHAR (50)  NULL,
    [Contract_Type]                                    VARCHAR (50)  NULL,
    [Terrain]                                          VARCHAR (50)  NULL,
    [CompanyNumber]                                    INT           NULL,
    [Field_ID]                                         INT           NULL,
    CONSTRAINT [PK_RESERVES_UPDATES_OIL_CONDENSATE] PRIMARY KEY CLUSTERED ([Id] ASC)
);

